"""initial schema

Revision ID: e0d92087c992
Revises: 
Create Date: 2026-08-19 00:59:03.014231
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e0d92087c992'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name IN ('ADMIN', 'ANALYST', 'VIEWER')", name='ck_roles_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule_definitions',
    sa.Column('rule_key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stream', sa.String(length=20), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_mandatory', sa.Boolean(), nullable=False),
    sa.Column('default_priority', sa.Integer(), nullable=False),
    sa.Column('parameter_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stream IN ('CALIBRATOR', 'CONTROL', 'PATIENT', 'OTHER', 'SKIPPED', 'NOT_IN_SCOPE')", name='ck_rule_definitions_stream'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_index('ix_rule_definitions_priority', 'rule_definitions', ['default_priority'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lowercase'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role_id', 'users', ['role_id'], unique=False)
    op.create_table('analytics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('analyte_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_analytics_is_active', 'analytics', ['is_active'], unique=False)
    op.create_index('uq_analytics_name_lower', 'analytics', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('analytics_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_at', 'audit_logs', ['action', 'at'], unique=False)
    op.create_index('ix_audit_logs_actor_at', 'audit_logs', ['actor_id', 'at'], unique=False)
    op.create_index('ix_audit_logs_analytics_at', 'audit_logs', ['analytics_id', 'at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_session', 'audit_logs', ['session_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('analytics_configuration_versions',
    sa.Column('analytics_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_config_version_positive'),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analytics_id', 'version', name='uq_config_version')
    )
    op.create_index('ix_config_versions_analytics_id', 'analytics_configuration_versions', ['analytics_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('analytics_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('header_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('empty_rows', sa.Integer(), nullable=True),
    sa.Column('malformed_rows', sa.Integer(), nullable=True),
    sa.Column('detected_analytes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('STORED', 'PARSED', 'INVALID')", name='ck_uploaded_files_status'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_uploaded_files_size'),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['uploaded_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index('ix_uploaded_files_analytics_uploaded_at', 'uploaded_files', ['analytics_id', 'uploaded_at'], unique=False)
    op.create_index('ix_uploaded_files_file_hash', 'uploaded_files', ['file_hash'], unique=False)
    op.create_index('ix_uploaded_files_status', 'uploaded_files', ['status'], unique=False)
    op.create_table('analytics_configurations',
    sa.Column('analytics_id', sa.UUID(), nullable=False),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['analytics_configuration_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analytics_id')
    )
    op.create_table('processing_sessions',
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('analytics_id', sa.UUID(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('parent_session_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_version_id', sa.UUID(), nullable=True),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('calibration_verdict', sa.String(length=20), nullable=False),
    sa.Column('control_verdict', sa.String(length=20), nullable=False),
    sa.Column('calibration_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('control_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gate_blocked_reason', sa.String(length=40), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('calibrator_rows', sa.Integer(), nullable=False),
    sa.Column('control_rows', sa.Integer(), nullable=False),
    sa.Column('patient_rows', sa.Integer(), nullable=False),
    sa.Column('other_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('started_by_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("calibration_verdict IN ('NOT_REVIEWED', 'PASS', 'FAIL')", name='ck_sessions_calibration_verdict'),
    sa.CheckConstraint("control_verdict IN ('NOT_REVIEWED', 'PASS', 'FAIL')", name='ck_sessions_control_verdict'),
    sa.CheckConstraint("state IN ('UPLOADED', 'VALIDATING', 'CALIBRATION_REVIEW', 'CALIBRATION_FAILED', 'CONTROL_REVIEW', 'CONTROL_FAILED', 'READY', 'PROCESSING_PATIENTS', 'COMPLETED', 'PROCESSING_FAILED')", name='ck_sessions_state'),
    sa.CheckConstraint('session_number >= 1', name='ck_sessions_number_positive'),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['config_version_id'], ['analytics_configuration_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_session_id'], ['processing_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uploaded_file_id', 'session_number', name='uq_session_number')
    )
    op.create_index('ix_sessions_analytics_created', 'processing_sessions', ['analytics_id', 'created_at'], unique=False)
    op.create_index('ix_sessions_file_number', 'processing_sessions', ['uploaded_file_id', 'session_number'], unique=False)
    op.create_index('ix_sessions_state', 'processing_sessions', ['state'], unique=False)
    op.create_table('calculation_traces',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adjustment_percent', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adjustment_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('lower_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('upper_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('result', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key IN ('ION_RATIO_RANGE', 'RT_WINDOW', 'CUTOFF', 'CALIBRATION_RANGE', 'ISTD_BASIS')", name='ck_calculation_traces_key'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'key', name='uq_trace_per_session_key')
    )
    op.create_index('ix_calculation_traces_session', 'calculation_traces', ['session_id'], unique=False)
    op.create_table('output_files',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('PASSED', 'EXCEPTIONS', 'SUMMARY')", name='ck_output_files_kind'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'kind', name='uq_output_per_session_kind'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index('ix_output_files_session_kind', 'output_files', ['session_id', 'kind'], unique=False)
    op.create_table('processing_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=True),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_events_session', 'processing_events', ['session_id', 'created_at'], unique=False)
    op.create_table('processing_rows',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stream', sa.String(length=20), nullable=False),
    sa.Column('sample_id', sa.String(length=200), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('analyte_name', sa.String(length=200), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('is_malformed', sa.Boolean(), nullable=False),
    sa.Column('parse_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stream IN ('CALIBRATOR', 'CONTROL', 'PATIENT', 'OTHER', 'SKIPPED', 'NOT_IN_SCOPE')", name='ck_processing_rows_stream'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'source_row_number', name='uq_session_row_number')
    )
    op.create_index('ix_processing_rows_sample_id', 'processing_rows', ['sample_id'], unique=False)
    op.create_index('ix_processing_rows_session_stream', 'processing_rows', ['session_id', 'stream'], unique=False)
    op.create_table('calibrator_selections',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('processing_row_id', sa.UUID(), nullable=False),
    sa.Column('calibrator_id', sa.String(length=100), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('value_state', sa.String(length=20), nullable=False),
    sa.Column('included_in_range', sa.Boolean(), nullable=False),
    sa.Column('percent_diff', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ion_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('found_rt', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('std_concentration', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('concentration', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('istd_area', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('threshold_used', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('selected_by_id', sa.UUID(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("validation_status IN ('PASS', 'FAIL', 'NOT_EVALUATED')", name='ck_calibrator_validation_status'),
    sa.CheckConstraint("value_state IN ('VALID', 'INVALID', 'MISSING', 'ZERO_EXCLUDED', 'UNSELECTED')", name='ck_calibrator_value_state'),
    sa.ForeignKeyConstraint(['processing_row_id'], ['processing_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'calibrator_id', name='uq_session_calibrator')
    )
    op.create_index('ix_calibrator_selections_session', 'calibrator_selections', ['session_id'], unique=False)
    op.create_table('control_selections',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('processing_row_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('value_state', sa.String(length=20), nullable=False),
    sa.Column('percent_diff', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ion_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('found_rt', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('std_concentration', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('concentration', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('threshold_used', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('selected_by_id', sa.UUID(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('REQUIRED', 'OPTIONAL', 'CUTOFF_SOURCE', 'DISCOVERED')", name='ck_control_role'),
    sa.CheckConstraint("validation_status IN ('PASS', 'FAIL', 'NOT_EVALUATED')", name='ck_control_validation_status'),
    sa.CheckConstraint("value_state IN ('VALID', 'INVALID', 'MISSING', 'ZERO_EXCLUDED', 'UNSELECTED')", name='ck_control_value_state'),
    sa.ForeignKeyConstraint(['processing_row_id'], ['processing_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'control_id', name='uq_session_control')
    )
    op.create_index('ix_control_selections_session', 'control_selections', ['session_id'], unique=False)
    op.create_table('processing_results',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('processing_row_id', sa.UUID(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=200), nullable=False),
    sa.Column('analyte_name', sa.String(length=200), nullable=True),
    sa.Column('final_result', sa.String(length=10), nullable=False),
    sa.Column('original_concentration', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adjusted_concentration', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cutoff_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('istd_area', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ion_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('found_rt', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rules_evaluated', sa.Integer(), nullable=False),
    sa.Column('rules_failed', sa.Integer(), nullable=False),
    sa.Column('failure_codes', postgresql.ARRAY(sa.String(length=60)), server_default='{}', nullable=False),
    sa.Column('evaluation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("final_result IN ('PASSED', 'FAILED')", name='ck_results_final_result'),
    sa.ForeignKeyConstraint(['processing_row_id'], ['processing_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'processing_row_id', name='uq_result_per_row')
    )
    op.create_index('ix_results_analyte_name', 'processing_results', ['analyte_name'], unique=False)
    op.create_index('ix_results_failure_codes', 'processing_results', ['failure_codes'], unique=False, postgresql_using='gin')
    op.create_index('ix_results_session_final', 'processing_results', ['session_id', 'final_result'], unique=False)
    op.create_index('ix_results_session_sample', 'processing_results', ['session_id', 'sample_id'], unique=False)
    op.create_table('row_corrections',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('processing_row_id', sa.UUID(), nullable=False),
    sa.Column('stream', sa.String(length=20), nullable=False),
    sa.Column('column_role', sa.String(length=60), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('corrected_by_id', sa.UUID(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stream IN ('CALIBRATOR', 'CONTROL', 'PATIENT', 'OTHER', 'SKIPPED', 'NOT_IN_SCOPE')", name='ck_row_corrections_stream'),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_row_corrections_reason_present'),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processing_row_id'], ['processing_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_row_corrections_row', 'row_corrections', ['processing_row_id', 'is_active'], unique=False)
    op.create_index('ix_row_corrections_session', 'row_corrections', ['session_id'], unique=False)
    op.create_table('rule_results',
    sa.Column('processing_result_id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=60), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('calculated_value', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Text(), nullable=True),
    sa.Column('lower_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('upper_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PASS', 'FAIL', 'SKIPPED')", name='ck_rule_results_status'),
    sa.ForeignKeyConstraint(['processing_result_id'], ['processing_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_results_key_status', 'rule_results', ['rule_key', 'status'], unique=False)
    op.create_index('ix_rule_results_result', 'rule_results', ['processing_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rule_results_result', table_name='rule_results')
    op.drop_index('ix_rule_results_key_status', table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_index('ix_row_corrections_session', table_name='row_corrections')
    op.drop_index('ix_row_corrections_row', table_name='row_corrections')
    op.drop_table('row_corrections')
    op.drop_index('ix_results_session_sample', table_name='processing_results')
    op.drop_index('ix_results_session_final', table_name='processing_results')
    op.drop_index('ix_results_failure_codes', table_name='processing_results', postgresql_using='gin')
    op.drop_index('ix_results_analyte_name', table_name='processing_results')
    op.drop_table('processing_results')
    op.drop_index('ix_control_selections_session', table_name='control_selections')
    op.drop_table('control_selections')
    op.drop_index('ix_calibrator_selections_session', table_name='calibrator_selections')
    op.drop_table('calibrator_selections')
    op.drop_index('ix_processing_rows_session_stream', table_name='processing_rows')
    op.drop_index('ix_processing_rows_sample_id', table_name='processing_rows')
    op.drop_table('processing_rows')
    op.drop_index('ix_processing_events_session', table_name='processing_events')
    op.drop_table('processing_events')
    op.drop_index('ix_output_files_session_kind', table_name='output_files')
    op.drop_table('output_files')
    op.drop_index('ix_calculation_traces_session', table_name='calculation_traces')
    op.drop_table('calculation_traces')
    op.drop_index('ix_sessions_state', table_name='processing_sessions')
    op.drop_index('ix_sessions_file_number', table_name='processing_sessions')
    op.drop_index('ix_sessions_analytics_created', table_name='processing_sessions')
    op.drop_table('processing_sessions')
    op.drop_table('analytics_configurations')
    op.drop_index('ix_uploaded_files_status', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_file_hash', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_analytics_uploaded_at', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_config_versions_analytics_id', table_name='analytics_configuration_versions')
    op.drop_table('analytics_configuration_versions')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_logs_session', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_analytics_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_analytics_name_lower', table_name='analytics')
    op.drop_index('ix_analytics_is_active', table_name='analytics')
    op.drop_table('analytics')
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_rule_definitions_priority', table_name='rule_definitions')
    op.drop_table('rule_definitions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
